version: '3.8'

services:
  backend-service:
    build:
      context: ..
      dockerfile: Dockerfile
    container_name: backend-service
    volumes:
      - ../src/:/usr/backend_app/src
    working_dir: /usr/backend_app
    ports:
      - "8080:8080"
    env_file:
      - ../.env
    command: python -m src
    networks:
      - app-network

networks:
  app-network:
    driver: bridge